include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.cscs.yml'

stages:
  - benchmark

benchmark:
  #extends: [".daint"]
  tags: ["kubernetes"]
  image: dropd/asv-upload-history:latest
  variables:
    PULL_IMAGE: "YES"
    SLURM_JOB_NUM_NODES: 1
    SLURM_TIMELIMIT: 10
  only:
    - main
    - trying
  stage: benchmark
  script:
    - mkdir -p ~/.ssh
    - cp "$DEPLOY_PRIVATE_KEY" ~/.ssh/id_asv
    - chmod 600 ~/.ssh/id_asv
    - pip install asv virtualenv
    - cp ./daint-node.json $HOME/.asv-machine.json
    - git checkout main && git pull --ff-only
    - asv run --machine daint-compute-node --show-stderr --skip-existing
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_asv -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
    - asv gh-pages
