include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.cscs.yml'

stages:
  - benchmark
  - publish

variables:
  UPLOAD_IMAGE: dropd/asv-upload-history:latest
  BENCHMARK_IMAGE: dropd/asv-upload-history:latest
  GITHUB_PATH: GridTools/cigrbench.git

.github_push_setup:
  before_script:
    - mkdir -p ~/.ssh
    - cp "$DEPLOY_PRIVATE_KEY" ~/.ssh/id_asv
    - chmod 600 ~/.ssh/id_asv
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_asv -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
    - git remote set-url origin git@github.com:${GITHUB_PATH}
    - git remote set-url --push origin git@github.com:${GITHUB_PATH}
    - git fetch

benchmark:
  extends: [".daint"]
  image: $BENCHMARK_IMAGE
  variables:
    PULL_IMAGE: "YES"
    SLURM_JOB_NUM_NODES: 1
    SLURM_TIMELIMIT: 10
  only:
    - main
    - trying
  stage: benchmark
  script:
    - pip install asv virtualenv
    - cp ./daint-node.json $HOME/.asv-machine.json
    - git remote add gh github.com/${GITHUB_PATH}
    - git fetch gh history || git branch gh/history  # we fetch or create the history branch from github
    - git checkout gh/history .asv || echo "no history"  # get the history if it exists
    - asv run --machine daint-compute-node --show-stderr --skip-existing
    - cp -r .asv $CI_PROJECT_DIR/results  # artifacts must be in the project dir
  artifacts:
    when: always
    paths:
      - results/

publish:
  extends: [".github_push_setup"]
  tags: ["kubernetes"]
  image: UPLOAD_IMAGE
  only:
    - main
    - trying
  stage: publish
  needs:
    - job: "benchmark"
      artifacts: true
  script:
    - git checkout history
    - cp -r ~/results .asv
    - git add -f .asv && git commit -m "update history"
    - git push
    - asv gh-pages
